# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# Generated by Django 5.2.15 on 2026-08-02 05:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trackingserver_template", "0002_alter_dagtemplate_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nodetemplate",
            name="classifications",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("transform", "Transform"),
                        ("data_saver", "DataSaver"),
                        ("data_loader", "DataLoader"),
                        ("input", "Input"),
                        ("placeholder", "Placeholder"),
                        ("result_builder", "ResultBuilder"),
                    ]
                ),
                size=None,
            ),
        ),
    ]
